### PR TITLE
Union Find

### PR DESCRIPTION
**Pull request by ChinthanBD**
```
[Running] python -u "c:\Users\cdevaraju\Desktop\123\code\CustomDS\union_find.py"
0
2
0
```

### CODE REVIEW

**Review by tejas-k3 — COMMENTED** [review]
Explain where this data structure is MOST impactful?

**Comment by ChinthanBD** [comment]
Social media sites like linkedIn, Snapchat, facebook etc where they show mutual connections

**Comment by tejas-k3** [comment]
But that can be done with Graph too?

**Comment by ChinthanBD** [comment]
Yes. But Union is specific for maintaining the cluster kind of structure and there is no need to use complex graph algorithm to traverse graph and find connected components

**Comment by tejas-k3** [comment]
Can we say?
'UNION FIND' data structure helps us in finding grouping (cluster) of elements and it shines in place where you want to do element classification and subset/superset finding, WHICH CAN ALSO BE DONE BY TRAVERSAL in "UNDIRECTED" Graph! But at the expense of O(n) time complexity.

**Comment by ChinthanBD** [comment]
Yes. This path compression concept makes is highly efficient

**Comment by tejas-k3** [comment]
Pls write the concept behind Union Find's high efficiency and let's merge this MR post that

**Comment by ChinthanBD** [comment]
The high efficiency of Union-Find comes from several optimizations:

1.Union by Rank or Size:

This optimization technique ensures that the depth of the resulting tree after performing Union operation is minimized.
In Union by Rank, the smaller tree is merged into the larger tree, which helps in keeping the depth of the tree minimal, thus optimizing the Find operation.

2.Path Compression:

This optimization technique flattens the structure of the trees representing sets during the Find operation.
When finding the root of an element, all nodes along the path are linked directly to the root, reducing the time complexity of future Find operations on the same elements.

3.Balancing Operations:

Techniques like Union by Rank or Size ensure that the resulting trees are balanced, preventing the worst-case scenario of having a tall tree, which would degrade the efficiency of Find operations.

4.Efficient Data Structure:

Implementation of Union-Find using efficient data structures like arrays or disjoint set forests contributes to its high efficiency.

**Comment by tejas-k3** [comment]
No copy paste please, write based off your understanding in way noob me can understand, try writing without any reference material 😊

**Comment by ChinthanBD** [comment]
Union find in mainly used in scenarios where cluster of elements come into place. 
It takes the related elements and groups them, so that all the elements in a single group is represented by a single element.
Representing all the elements of a group by a single element makes the 'find' operation sufficient.
Further the technique like path compression where the element is pointed to representative element directly instead of having other elements between representative element and any given element makes the lookup faster

**Pull request merged**
